apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-admin-pods-label
  template:
    metadata:
      name: portal-admin-pod
      labels:
        app: portal-admin-pods-label
    spec:
      containers:
      - name: portal-admin-container
        image: {{ .Values.image.repository }}/{{ .Values.image.project }}/portal-admin:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 18082
        # resources:
        #   limits:
        #     memory: "1000Mi"
        #     cpu: "1000m"
        #   requests:
        #     memory: "1000Mi"
        #     cpu: "1000m"
        envFrom:
        - configMapRef:
            name: spring-vault-cm
        - configMapRef:
            name: spring-mail-cm
        - configMapRef:
            name: spring-redis-cm
        - configMapRef:
            name: logging-level-cm
      imagePullSecrets:
      - name: harborcred

---

apiVersion: v1
kind: Service
metadata:
  name: svc-portal-admin
spec:
  ports:
    - name: portal-admin-port
      port: 18082
      targetPort: 18082
  selector:
    app: portal-admin-pods-label
  type: ClusterIP
