apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-cm
data:
  {{- with .Values.keycloak }}
  CLOUDPLATFORM_KEYCLOAK_USER_AT: {{ .userAt | quote }}
  CLOUDPLATFORM_KEYCLOAK_ADMIN_CLI_ID: {{ .admin.id | quote }}
  CLOUDPLATFORM_KEYCLOAK_ADMIN_CLI_PW: {{ .admin.pw | quote }}
  CLOUDPLATFORM_KEYCLOAK_CLIENT_ID: {{ .client.id | quote }}
  CLOUDPLATFORM_KEYCLOAK_CLIENT_SECRET: {{ .client.secret | quote }}
  CLOUDPLATFORM_KEYCLOAK_REALM: {{ .realm | quote }}
  CLOUDPLATFORM_KEYCLOAK_URL: {{ .url | quote }}
  {{- end }}

