apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-mail-cm
data:
  {{- with .Values.mail }}
  SPRING_MAIL_HOST: {{ .host | quote }}
  SPRING_MAIL_USERNAME: {{ .username | quote }}
  SPRING_MAIL_PASSWORD: {{ .password | quote }}
  SPRING_MAIL_PORT: {{ .port | quote }}
  {{- end }}


