apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-jpa-cm
data:
  {{- with .Values.jpa }}
  SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: {{ .hibernate.showSQL | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: {{ .hibernate.formatSQL | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: {{ .hibernate.useSQLComment | quote }}
  SPRING_JPA_GENERATE_DDL: {{ .gernerateDDL | quote }}
  SPRING_JPA_DATABASE_PLATFORM: {{ .database.platform | quote }}
  {{- end }}

