apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-service-broker-pvc
spec:
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi