apiVersion: v1
kind: Secret
metadata:
  name: harborcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2hhcmJvci5va2VzdHJvLmNsZC92Mi8iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoib2tlc3RybzIwMTgiLCJlbWFpbCI6InNrLmthbmdAb2tlc3Ryby5jb20iLCJhdXRoIjoiWVdSdGFXNDZiMnRsYzNSeWJ6SXdNVGc9In19fQ==
